# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Q-Zine
email: qzine.teebo@spamgourmet.com
description: > # this means to ignore newlines until "baseurl:"
  Recettes pour le quotidien, pour le bateau, pour les sorties de groupes, ...
baseurl: "/Q-Zine" # the subpath of your site, e.g. /blog
url: "https://TeebObeeT.github.io" # the base hostname & protocol for your site
github_username:  TeebObeeT
safe: true

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown
